import Link from "next/link";
import { db } from "@/lib/db";
import { notFound } from "next/navigation";
import { formatGhs } from "@/lib/money";
import { regionLabel } from "@/lib/regions";
import { computeInsights } from "@/lib/concierge/insights";
import InsightsStrip from "@/components/Concierge/InsightsStrip";

function daysUntil(d: Date) {
  const ms = d.getTime() - Date.now();
  return Math.ceil(ms / (1000 * 60 * 60 * 24));
}

export default async function EventOverview({
  params,
}: {
  params: Promise<{ eventId: string }>;
}) {
  const { eventId } = await params;
  const [event, giftAgg] = await Promise.all([
    db.event.findUnique({
      where: { id: eventId },
      include: {
        _count: { select: { guests: true } },
        rsvps: { select: { status: true } },
        budget: { select: { totalMinor: true, generatedByAi: true } },
      },
    }),
    db.gift.aggregate({
      where: { eventId },
      _sum: { amountMinor: true },
      _count: true,
    }),
  ]);
  if (!event) notFound();

  const insights = await computeInsights(event.id).catch(() => []);

  const counts = event.rsvps.reduce(
    (acc, r) => {
      acc[r.status] = (acc[r.status] ?? 0) + 1;
      return acc;
    },
    {} as Record<string, number>,
  );

  const dUntil = daysUntil(event.eventDate);

  return (
    <div className="space-y-6">
      {insights.length > 0 && <InsightsStrip eventId={event.id} insights={insights} />}
      <div className="card flex flex-col items-start justify-between gap-4 md:flex-row md:items-center">
        <div>
          <p className="text-sm text-ink-600">Wedding</p>
          <h1 className="mt-1 font-display text-3xl font-semibold text-ink-900">
            {event.title}
          </h1>
          <p className="mt-1 text-ink-700">
            {event.eventDate.toLocaleDateString("en-GH", {
              weekday: "long",
              year: "numeric",
              month: "long",
              day: "numeric",
            })}{" "}
            · {event.city}, {regionLabel(event.region)}
          </p>
        </div>
        <div className="text-right">
          <p className="text-sm text-ink-600">Time until</p>
          <p className="font-display text-4xl font-semibold text-kente-700">
            {dUntil > 0 ? `${dUntil}d` : dUntil === 0 ? "Today!" : `${-dUntil}d ago`}
          </p>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="card">
          <p className="text-sm text-ink-600">Guests on the list</p>
          <p className="mt-1 font-display text-3xl font-semibold text-ink-900">
            {event._count.guests}
          </p>
          <p className="mt-2 text-sm text-ink-500">Target: {event.guestCount}</p>
          <Link href={`/dashboard/${event.id}/guests`} className="btn-secondary mt-4 text-sm">
            Manage guests
          </Link>
        </div>

        <div className="card">
          <p className="text-sm text-ink-600">RSVPs</p>
          <p className="mt-1 font-display text-3xl font-semibold text-ink-900">
            {(counts.yes ?? 0) + (counts.no ?? 0) + (counts.maybe ?? 0)}
          </p>
          <div className="mt-2 flex flex-wrap gap-2 text-xs">
            <span className="chip bg-forest-100 text-forest-800">
              Yes · {counts.yes ?? 0}
            </span>
            <span className="chip bg-amber-100 text-amber-800">
              Maybe · {counts.maybe ?? 0}
            </span>
            <span className="chip bg-red-100 text-red-800">No · {counts.no ?? 0}</span>
          </div>
        </div>

        <div className="card">
          <p className="text-sm text-ink-600">Gifts received</p>
          <p className="mt-1 font-display text-3xl font-semibold text-ink-900">
            {formatGhs(giftAgg._sum.amountMinor ?? 0)}
          </p>
          <p className="mt-2 text-sm text-ink-500">
            {giftAgg._count} {giftAgg._count === 1 ? "gift" : "gifts"} so far
          </p>
          <Link href={`/dashboard/${event.id}/gifts`} className="btn-secondary mt-4 text-sm">
            See gifts & thank guests
          </Link>
        </div>

        <div className="card">
          <p className="text-sm text-ink-600">Budget</p>
          <p className="mt-1 font-display text-3xl font-semibold text-ink-900">
            {event.budget ? formatGhs(event.budget.totalMinor) : "—"}
          </p>
          <p className="mt-2 text-sm text-ink-500">
            {event.budget?.generatedByAi
              ? "Generated by Claude"
              : event.budget
                ? "From template"
                : "Not yet generated"}
          </p>
          <Link href={`/dashboard/${event.id}/budget`} className="btn-secondary mt-4 text-sm">
            {event.budget ? "Review budget" : "Generate budget"}
          </Link>
        </div>
      </div>

      <div className="rounded-2xl bg-gradient-to-br from-kente-500 via-kente-600 to-forest-700 p-6 text-white shadow-soft">
        <p className="text-xs uppercase tracking-widest opacity-90">New</p>
        <h2 className="mt-1 font-display text-2xl font-semibold">Design your site with AI</h2>
        <p className="mt-1 max-w-xl opacity-95">
          Tell Claude one paragraph about you and your wedding. It writes your hero, story,
          schedule, FAQ, and gift section — tuned to a Ghanaian wedding. Edit anything inline,
          regenerate sections, or swap the template in one click.
        </p>
        <Link
          href={`/dashboard/${event.id}/design`}
          className="btn-secondary mt-4 inline-flex bg-white text-ink-900 hover:bg-ink-50"
        >
          Open Design Studio →
        </Link>
      </div>

      <div className="card">
        <h2 className="font-display text-xl font-semibold text-ink-900">Share your event page</h2>
        <p className="mt-1 text-ink-700">
          Send this link to guests. They&apos;ll see your page and can RSVP and send MoMo cash gifts (gifts coming soon).
        </p>
        <div className="mt-3 flex items-center gap-2">
          <code className="flex-1 truncate rounded-xl bg-ink-100 px-3 py-2 text-sm text-ink-900">
            {process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"}/e/{event.slug}
          </code>
          <Link href={`/e/${event.slug}`} className="btn-primary text-sm">
            View page
          </Link>
        </div>
      </div>
    </div>
  );
}
