"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { formatGhs } from "@/lib/money";

interface BudgetItem {
  category: string;
  label: string;
  plannedMinor: number;
  lowMinor: number;
  highMinor: number;
  notes: string | null;
}

interface Budget {
  totalMinor: number;
  generatedByAi: boolean;
  assumptions: string[];
  warnings: string[];
  items: BudgetItem[];
}

export default function BudgetClient({
  eventId,
  eventTitle,
  initialBudget,
}: {
  eventId: string;
  eventTitle: string;
  initialBudget: Budget | null;
}) {
  const router = useRouter();
  const [budget, setBudget] = useState<Budget | null>(initialBudget);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState<"ai" | "template" | null>(
    initialBudget ? (initialBudget.generatedByAi ? "ai" : "template") : null,
  );

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/events/${eventId}/budget`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error ?? "Failed to generate budget");
        return;
      }
      const b: Budget = {
        totalMinor: data.budget.totalMinor,
        generatedByAi: data.budget.generatedByAi,
        assumptions: data.budget.assumptions,
        warnings: data.budget.warnings,
        items: data.budget.items.map((i: BudgetItem) => i),
      };
      setBudget(b);
      setSource(data.source);
      router.refresh();
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      <div className="card flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="font-display text-2xl font-semibold text-ink-900">Budget for {eventTitle}</h1>
          <p className="mt-1 text-sm text-ink-600">
            Realistic line-item budget in GHS, tuned to your region and guest count.
          </p>
        </div>
        <button onClick={generate} className="btn-primary" disabled={loading}>
          {loading ? "Working…" : budget ? "Regenerate" : "Generate with AI"}
        </button>
      </div>

      {error && <p className="text-sm text-red-600">{error}</p>}

      {!budget ? (
        <div className="card text-center">
          <p className="text-ink-600">
            No budget yet. Click <span className="font-medium">Generate with AI</span> to create one.
          </p>
        </div>
      ) : (
        <>
          <div className="card">
            <div className="flex flex-wrap items-end justify-between gap-3">
              <div>
                <p className="text-sm text-ink-600">Total (typical)</p>
                <p className="font-display text-4xl font-semibold text-ink-900">
                  {formatGhs(budget.totalMinor)}
                </p>
              </div>
              <span className="chip bg-kente-100 text-kente-800">
                {source === "ai" ? "✨ Generated by Claude" : "Template (set ANTHROPIC_API_KEY for AI)"}
              </span>
            </div>
            {budget.warnings.length > 0 && (
              <div className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-900 ring-1 ring-amber-200">
                <p className="font-medium">Heads up</p>
                <ul className="mt-1 list-disc pl-5">
                  {budget.warnings.map((w, i) => (
                    <li key={i}>{w}</li>
                  ))}
                </ul>
              </div>
            )}
            {budget.assumptions.length > 0 && (
              <div className="mt-3 rounded-xl bg-ink-100 px-4 py-3 text-sm text-ink-700">
                <p className="font-medium">Assumptions</p>
                <ul className="mt-1 list-disc pl-5">
                  {budget.assumptions.map((a, i) => (
                    <li key={i}>{a}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          <div className="card overflow-hidden p-0">
            <table className="w-full text-left text-sm">
              <thead className="bg-ink-50 text-xs uppercase tracking-wide text-ink-600">
                <tr>
                  <th className="px-5 py-3">Category</th>
                  <th className="px-5 py-3 text-right">Low</th>
                  <th className="px-5 py-3 text-right">Typical</th>
                  <th className="px-5 py-3 text-right">High</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-ink-100">
                {budget.items.map((it) => (
                  <tr key={it.category}>
                    <td className="px-5 py-3">
                      <p className="font-medium text-ink-900">{it.label}</p>
                      {it.notes && <p className="text-xs text-ink-500">{it.notes}</p>}
                    </td>
                    <td className="px-5 py-3 text-right text-ink-600">
                      {formatGhs(it.lowMinor)}
                    </td>
                    <td className="px-5 py-3 text-right font-medium text-ink-900">
                      {formatGhs(it.plannedMinor)}
                    </td>
                    <td className="px-5 py-3 text-right text-ink-600">
                      {formatGhs(it.highMinor)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
}
